server:
  port: 8025

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
