spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: nameRoot
          uri: lb://app1
          predicates:
            - Path=/api/gateway/l1/**
          filters:
            - StripPrefix=2
server:
  port: 80
#注册中心
eureka:
  client:
    #设置服务注册中心的URL
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}