spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: app1
          predicates:
          - Path=/client/**
          uri: lb://APP1
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@userKeyResolver}'
                redis-rate-limiter.replenishRate: 1 # 允许每秒处理了多少个请求
                redis-rate-limiter.burstCapacity: 1 # 令牌桶的容量（最高处理并发容量大小1）
APP1:
  ribbon:
    NFLoadBalancerRuleClassName: com.mark.gateway.filter.MyRule

server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}