spring:
  application:
    name: mark-client2
server:
  port: 8089

feign:
  compression:
    request:
      mime-types:
        - text/xml
      min-request-size: 2048

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}


