spring:
  application:
    name: mark-client1
server:
  port: 8081

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
    virtual-host-name: mark-client1
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    lease-renewal-interval-in-seconds: 1
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-expiration-duration-in-seconds: 1
